apiVersion: apps/v1
kind: Deployment
metadata:
  name: erp-api-gateway-deployment
  namespace: erp-prod
  labels:
    app: erp-api-gateway
    environment: production
spec:
  replicas: 2
  selector:
    matchLabels:
      app: erp-api-gateway
  template:
    metadata:
      labels:
        app: erp-api-gateway
    spec:
      containers:
      - name: erp-api-gateway
        image: erp-api-gateway:1.0.0-SNAPSHOT  # Sera remplacé par l'image ECR
        ports:
        - containerPort: 8014
        env:
        - name: SPRING_PROFILES_ACTIVE
          valueFrom:
            configMapKeyRef:
              name: erp-config
              key: SPRING_PROFILES_ACTIVE
        - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
          valueFrom:
            configMapKeyRef:
              name: erp-config
              key: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
        - name: SPRING_CLOUD_CONFIG_URI
          valueFrom:
            configMapKeyRef:
              name: erp-config
              key: SPRING_CLOUD_CONFIG_URI
        - name: JAVA_OPTS
          valueFrom:
            configMapKeyRef:
              name: erp-config
              key: JAVA_OPTS
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8014
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8014
          initialDelaySeconds: 30
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: erp-api-gateway-service
  namespace: erp-prod
  labels:
    app: erp-api-gateway
    environment: production
spec:
  selector:
    app: erp-api-gateway
  ports:
  - port: 8014
    targetPort: 8014
    protocol: TCP
  type: LoadBalancer  # Exposé pour l'accès externe
