apiVersion: apps/v1
kind: Deployment
metadata:
  name: erp-config-deployment
  namespace: erp-prod
  labels:
    app: erp-config
    environment: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: erp-config
  template:
    metadata:
      labels:
        app: erp-config
    spec:
      containers:
      - name: erp-config
        image: erp-config:1.0.0-SNAPSHOT  # Sera remplacé par l'image ECR
        ports:
        - containerPort: 8012
        env:
        - name: SPRING_PROFILES_ACTIVE
          valueFrom:
            configMapKeyRef:
              name: erp-config
              key: SPRING_PROFILES_ACTIVE
        - name: JAVA_OPTS
          value: "-Xmx512m -Xms256m"
        - name: SPRING_CLOUD_CONFIG_SERVER_GIT_DEFAULT_LABEL
          value: "master"
        resources:
          requests:
            memory: "256Mi"
            cpu: "125m"
          limits:
            memory: "512Mi"
            cpu: "250m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8012
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8012
          initialDelaySeconds: 30
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: erp-config-service
  namespace: erp-prod
  labels:
    app: erp-config
    environment: production
spec:
  selector:
    app: erp-config
  ports:
  - port: 8012
    targetPort: 8012
    protocol: TCP
  type: ClusterIP
