apiVersion: v1
kind: Secret
metadata:
  name: erp-secrets
  namespace: erp-prod
  labels:
    app: erp-secrets
    environment: production
type: Opaque
data:
  # Database Password (base64 encoded)
  DB_PASSWORD: ZXJwX3Bhc3N3b3JkXzIwMjQ=  # erp_password_2024
  
  # Keycloak Client Secret (base64 encoded)
  KEYCLOAK_CLIENT_SECRET: eW91ci1jbGllbnQtc2VjcmV0  # your-client-secret
  
  # Keycloak Admin Password (base64 encoded)
  KEYCLOAK_ADMIN_PASSWORD: cGFzc3cwcmQ=  # passw0rd
