apiVersion: apps/v1
kind: Deployment
metadata:
  name: erp-user-service-deployment
  namespace: erp-prod
  labels:
    app: erp-user-service
    environment: production
spec:
  replicas: 2
  selector:
    matchLabels:
      app: erp-user-service
  template:
    metadata:
      labels:
        app: erp-user-service
    spec:
      containers:
      - name: erp-user-service
        image: erp-user-service:1.0.0-SNAPSHOT  # Sera remplacé par l'image ECR
        ports:
        - containerPort: 8055
        env:
        - name: SPRING_PROFILES_ACTIVE
          valueFrom:
            configMapKeyRef:
              name: erp-config
              key: SPRING_PROFILES_ACTIVE
        - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
          valueFrom:
            configMapKeyRef:
              name: erp-config
              key: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
        - name: SPRING_CLOUD_CONFIG_URI
          valueFrom:
            configMapKeyRef:
              name: erp-config
              key: SPRING_CLOUD_CONFIG_URI
        - name: DB_URL
          valueFrom:
            configMapKeyRef:
              name: erp-config
              key: DB_URL
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: erp-config
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: erp-secrets
              key: DB_PASSWORD
        - name: KEYCLOAK_URL
          valueFrom:
            configMapKeyRef:
              name: erp-config
              key: KEYCLOAK_URL
        - name: KEYCLOAK_REALM
          valueFrom:
            configMapKeyRef:
              name: erp-config
              key: KEYCLOAK_REALM
        - name: KEYCLOAK_CLIENT_ID
          valueFrom:
            configMapKeyRef:
              name: erp-config
              key: KEYCLOAK_CLIENT_ID
        - name: KEYCLOAK_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: erp-secrets
              key: KEYCLOAK_CLIENT_SECRET
        - name: KEYCLOAK_ADMIN_USERNAME
          valueFrom:
            configMapKeyRef:
              name: erp-config
              key: KEYCLOAK_ADMIN_USERNAME
        - name: KEYCLOAK_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: erp-secrets
              key: KEYCLOAK_ADMIN_PASSWORD
        - name: JAVA_OPTS
          valueFrom:
            configMapKeyRef:
              name: erp-config
              key: JAVA_OPTS
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8055
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8055
          initialDelaySeconds: 30
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: erp-user-service-service
  namespace: erp-prod
  labels:
    app: erp-user-service
    environment: production
spec:
  selector:
    app: erp-user-service
  ports:
  - port: 8055
    targetPort: 8055
    protocol: TCP
  type: ClusterIP
