version: '3.8'

services:
  # Keycloak with auto creation of realm
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.3
    container_name: keycloak
    command: start-dev --import-realm --features=account-api,account2  --spi-account-rest-api-account-rest-api-enabled=true  --spi-account-rest-api-enabled=true

    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: passw0rd
#     KC_SPI_ACCOUNT_REST_API_ACCOUNT_REST_API_ENABLED: "true"
#     KC_SPI_ACCOUNT_REST_API_ENABLED: true (remplace --spi-account-rest-api-enabled=true) pour activer les api de profile
    volumes:
#      - ./.keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json
      - ./.keycloak/erp-realm-export.json:/opt/keycloak/data/import/erp-realm-export.json
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE:  achat_db
      MYSQL_USER: ahlem
      MYSQL_PASSWORD: achat
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - spring_network

networks:
  spring_network:
    driver: bridge

volumes:
  mysql_data: