spring:
  application:
    name: erp-service-discovery
  cloud:
    config:
      uri: ${SPRING_CLOUD_CONFIG_URI:http://localhost:8012}
      profile: ${SPRING_PROFILES_ACTIVE:dev}
  config:
    import: "configserver:${SPRING_CLOUD_CONFIG_URI:http://localhost:8012}"