spring:
  application:
    name: erp-inventory-service
  datasource:
    url: jdbc:mysql://localhost:3306/achat_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false
  mvc:
    contentnegotiation:
      media-types:
        json: application/json
        json-utf8: application/json;charset=UTF-8
  web:
    resources:
      add-mappings: false
  servlet:
    context-path: /

server:
  port: 8059

eureka:
  client:
    enabled: false
  instance:
    enabled: false

logging:
  level:
    com.iss4u.erp.services: DEBUG
    org.springframework.web: DEBUG

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false
