spring:
  application:
    name: erp-sales-service
  profiles:
    active: local
  # Configuration locale par défaut pour éviter les problèmes de config server
  # config:
  #   import: "configserver:http://localhost:8012"
  # cloud:
  #   config:
  #     profile: ${spring.profiles.active}