spring:
  application:
    name: erp-client-service
  profiles:
    active: ultra-simple
  # Configuration ultra-simple par défaut
  jackson:
    generator:
      write-numbers-as-strings: false
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false
      fail-on-empty-beans: false
      write-null-map-values: false
      fail-on-self-references: false
      write-self-references-as-null: true
      indent-output: false
      disable-circular-reference-detection: true
    deserialization:
      fail-on-unknown-properties: false
      disable-circular-reference-detection: true
    parser:
      max-nesting-depth: 10
    mapper:
      disable-circular-reference-detection: true
  jpa:
    properties:
      hibernate:
        enable_lazy_load_no_trans: false
        default_batch_fetch_size: 0
        jdbc:
          batch_size: 0
        order_inserts: false
        order_updates: false
        batch_versioned_data: false
        lazy_loading: false
        collection:
          lazy_extra: false
        bidirectional_relation:
          ignore: true
        relation:
          ignore: true
server:
  port: 8058
eureka:
  client:
    enabled: false
  instance:
    enabled: false
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
