server:
  port: 8058

spring:
  application:
    name: erp-client-service
  jackson:
    generator:
      write-numbers-as-strings: false
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false
      fail-on-empty-beans: false
      write-null-map-values: false
      fail-on-self-references: false
      write-self-references-as-null: true
      indent-output: false
    deserialization:
      fail-on-unknown-properties: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        enable_lazy_load_no_trans: false
        default_batch_fetch_size: 0
        jdbc:
          batch_size: 0
        order_inserts: false
        order_updates: false
        batch_versioned_data: false
        lazy_loading: false
        collection:
          lazy_extra: false
        bidirectional_relation:
          ignore: true
        relation:
          ignore: true
  datasource:
    url: jdbc:mysql://localhost:3306/achat_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    hikari:
      minimum-idle: 1
      maximum-pool-size: 5
      idle-timeout: 300000
      max-lifetime: 1200000
      connection-timeout: 20000
      validation-timeout: 3000
      leak-detection-threshold: 60000
      housekeeping-period-ms: 0
      keepalive-time: 0
      connection-test-query: SELECT 1
  cloud:
    config:
      enabled: false

# Désactiver Eureka pour le mode ultra-simple
eureka:
  client:
    enabled: false
  instance:
    enabled: false

# Configuration CORS
cors:
  allowed-origins: "*"
  allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
  allowed-headers: "*"
  allow-credentials: false

# Logging ultra-strict
logging:
  level:
    com.iss4u.erp: WARN
    org.springframework.web: WARN
    com.zaxxer.hikari: WARN
    org.hibernate: ERROR
    org.springframework.orm: ERROR
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
