spring:
  application:
    name: erp-user-service
  cloud:
    config:
      uri: ${SPRING_CLOUD_CONFIG_URI:http://localhost:8012}
      profile: ${SPRING_PROFILES_ACTIVE:dev}
  config:
    import: "configserver:${SPRING_CLOUD_CONFIG_URI:http://localhost:8012}"
      profile: ${spring.profiles.active}

# Configuration Keycloak
keycloak:
  server-url: http://localhost:8080
  realm: erp-realm
  client-id: admin-cli
  username: ahlem.cherni
  password: ahlem1234

# Configuration des logs
logging:
  level:
    com.iss4u.erp.services: DEBUG
    org.keycloak: INFO