server:
  port: 8014

spring:
  application:
    name: erp-user-service
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  h2:
    console:
      enabled: true

# Configuration Keycloak
keycloak:
  auth-server-url: http://localhost:8081
  realm: erp-realm
  resource: erp-backend
  credentials:
    secret: your-secret-here
  bearer-only: true

# Configuration CORS
cors:
  allowed-origins: "http://localhost:4200"
  allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
  allowed-headers: "*"
  allow-credentials: true

# Logging
logging:
  level:
    com.iss4u.erp: DEBUG
    org.springframework.web: DEBUG
