spring:
  application:
    name: erp-user-service
  cloud:
    config:
      uri: ${SPRING_CLOUD_CONFIG_URI:http://localhost:8012}
      profile: ${SPRING_PROFILES_ACTIVE:dev}
  config:
    import: "configserver:${SPRING_CLOUD_CONFIG_URI:http://localhost:8012}"

# Configuration Keycloak
keycloak:
  server-url: ${KEYCLOAK_URL:http://localhost:8080}
  realm: ${KEYCLOAK_REALM:erp-realm}
  client-id: ${KEYCLOAK_CLIENT_ID:admin-cli}
  username: ${KEYCLOAK_ADMIN_USERNAME:ahlem.cherni}
  password: ${KEYCLOAK_ADMIN_PASSWORD:ahlem1234}

# Configuration des logs
logging:
  level:
    com.iss4u.erp.services: DEBUG
    org.keycloak: INFO